config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  root 'static_pages#home'
  
  get 'users/new'

  get 'static_pages/home'

  get 'static_pages/category'
  
  get 'static_pages/locations'
  
  get 'static_pages/media'

  get  '/signup',  to: 'users#new'
  
  post '/signup',  to: 'users#create'
  
  get    '/login',   to: 'sessions#new'
   
  post   '/login',   to: 'sessions#create'
  
  delete '/logout',  to: 'sessions#destroy'
  
    get  '/browseallcourses',  to: 'static_pages#course'

 
  resources :users
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  before_save { self.email = email.downcase }
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  # Remembers a user in the database for use in persistent sessions.
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in @user
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_to @user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def category
  end
  
  def locations
  end
  
  def media
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Course App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '') 
    base_title = "Ruby on Rails Tutorial Course App" 
    if page_title.empty?
     base_title 
     else 
       page_title + " | " + base_title 
       end 
       end
  end

app/helpers/sessions_helper.rb
module SessionsHelper

  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end

  # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

 # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, size: 80)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/category.html.erb
<% provide(:title, "Category") %>
<h1>Category</h1> 
<p>
      Get category on the Ruby on Rails Tutorial at the 
      <a href="http://www.railstutorial.org/help">Rails Tutorial category 
      page</a>.

To get category on this course app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails 
Tutorial</em> book</a>.
</p> 
>

app/views/static_pages/course.html.erb
<% provide(:title, 'Browse all courses') %>
<head>
	<title>All course</title>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">

	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>
	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
	
</head>
<body>

<div class="container">
<div class="d-flex justify-content-center">
		           	<h1>All course</h1>
		           </div>
		           <hr>

		        

		           <div>
		           	<ul class="nav nav-tabs" id="myTab" role="tablist">
		           		<li class="nav-item">
		           			<a class="nav-link active" id="course-tab" data-toggle="tab" href="#course" role="tab" aria-controls="course" aria-selected="true"><font style="font-size: 12px"><b>Course</b></font></a>
		           		</li>
		           		<li class="nav-item">
		           			<a class="nav-link" id="coordinator-tab" data-toggle="tab" href="#coordinator" role="tab" aria-controls="coordinator" aria-selected="false"><font style="font-size: 12px"><b>Coordinator</b></font></a>
		           		</li>

		           	</ul>

		           
		           	<div class="tab-content" id="myTabContent">
		           		<div class="tab-pane fade show active" id="course" role="tabpanel" aria-labelledby="course-tab">
		           			<div class="row">
		           				<div class="col-sm-2">
		           					<img src="http://pic1.qqmofasi.com/2015/06/06/1793_DfpZf0HOI0g0OzhG0gpF_square.jpg" class="rounded mx-auto d-block" style="width: 100px; height: 100px;"><br>
		           					<p class="text-center" style="font-size: 14px"><b>Coordinato name: Andy Song</b></p>

		           				</div>
		           				
		           				<div class="col-sm-7" >
		           					<br>
		           					<p style="font-size: 20px; color: #0000CD;"><b>Rpid Application Development</b></p>
		           					<p>Prerequisite: Web Programming</p>
		           					<p>Category: Web Development</p>
		           					<p>Location: 14.10.31	14.08.26</p>
		           					<p>Creasted: 15 days ago</p>
		           					<p class="text-right">finger1，finger2</p>
		           					
		           				</div>
		           			</div>
		           			<br>
		           			<hr>
		           			<div class="row">
		           				<div class="col-sm-2">
		           					<img src="http://pic1.qqmofasi.com/2015/06/06/1793_DfpZf0HOI0g0OzhG0gpF_square.jpg" class="rounded mx-auto d-block" style="width: 100px; height: 100px;"><br>
		           					<p class="text-center" style="font-size: 14px">Coordinato name: Andy Song</p>

		           				</div>
		           				
		           				<div class="col-sm-7" >
		           					<br>
		           					<p style="font-size: 20px; color: #0000CD;">Capstone Project</p>
		           					<p>Prerequisite: Advanced Programming</p>
		           					<p>Category: Full Stack Dev</p>
		           					<p>Location: 14.10.31</p>
		           					<p>Creasted: 5 minutes ago</p>
		           					<p class="text-right">finger1，finger2</p>

		           				</div>
		           			</div>
		           			<br>
		           			<hr>
		           			<div class="row">
		           				<div class="col-sm-2">
		           					<img src="http://pic3.qqmofasi.com/2015/06/06/1793_uexxQjT5J5PpIjsReTV3_square.jpg" class="rounded mx-auto d-block" style="width: 100px; height: 100px;"><br>
		           					<p class="text-center" style="font-size: 14px">Coordinato name: Alex Jiang</p>

		           				</div>
		           				
		           				<div class="col-sm-7" >
		           					<br>
		           					<p style="font-size: 20px; color: #0000CD;">Advanced iOS/OSX Programming</p>
		           					<p>Prerequisite: 3 years iOS or relevant experience</p>
		           					<p>Category: iOS Engineering</p>
		           					<p>Location: 14.10.30</p>
		           					<p>Creasted: 8 days ago</p>
		           					<p class="text-right">finger1，finger2</p>

		           				</div>
		           			</div>
		           		</div>


<div class="tab-pane fade" id="coordinator" role="tabpanel" aria-labelledby="coordinator-tab">
		           			<div class="d-flex justify-content-center ">
		           				<table>
		           					<tr>
		           						<td>
		           							<img src="http://pic1.qqmofasi.com/2015/06/06/1793_DfpZf0HOI0g0OzhG0gpF_square.jpg"><br>
		           							<p class="d-flex justify-content-center ">Coordinato name: Andy Song</p>
		           						</td>
		           					</tr>
		           					<tr>
		           						<td>
		           							<img src="http://pic3.qqmofasi.com/2015/06/06/1793_uexxQjT5J5PpIjsReTV3_square.jpg" class="rounded mx-auto d-block"><br>
		           							<p class="d-flex justify-content-center ">Coordinato name: Alex Jiang</p>
		           						</td>
		           					</tr>
		           					<tr>
		           						<td>
		           							<img src="http://pic1.qqmofasi.com/2015/06/06/1793_DfpZf0HOI0g0OzhG0gpF_square.jpg" class="rounded mx-auto d-block"><br>
		           							<p class="d-flex justify-content-center ">Coordinato name: Ali Yavari</p>
		           						</td>
		           					</tr>
		           				</table>
		           			</div>
		           		</div>

		           	</div>
		           </div>


		       </div>
		   </body>
		  

app/views/static_pages/home.html.erb
<div class="center jumbotron">
<h1>Welcome to Your Course App</h1> 

<h2>
    This is the home page for the RAD Assignment 2
</h2>


  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %> 
 </div>


<h3></h3>
<ul class="list-inline">
<li>
    <dl>
    <dt>View Course as Guest User</dt>
    <dd>Browse and view courses as a guest and </dd>
    <dd>sign up later</dd>
    </dl>
      <%= link_to "Browse all courses", browseallcourses_path, class: "btn btn-lg btn-primary" %> 

    </li>
     
 <li>
     <dl>
     <dt>Sign in to your account</dt> 
     <dd>Update your courses, rate courses, view </dd>
     <dd>coordinator informations</dd>
     </dl>
     <button type="button" class="btn btn-success">
         <span class="glyphicon glyphicon-user"></span> Log in to your account</button>
     </li>
    
 </ul>
 
 

app/views/static_pages/locations.html.erb
<% provide(:title, "Locations") %>
<h1>Locations</h1>
<p>
      Get locations on the Ruby on Rails Tutorial at the 
      <a href="http://www.railstutorial.org/help">Rails Tutorial locations 
      page</a>.

To get locations on this course app, see the
<a href="http://www.railstutorial.org/book"><em>Ruby on Rails 
Tutorial</em> book</a>.
</p> 

app/views/static_pages/media.html.erb
<% provide(:title, "Media") %>
<h1>Media</h1>  
<p> 
The <a href="http://www.railstutorial.org/"><em>Ruby on Rails 
Tutorial</em></a> is a 
<a href="http://www.railstutorial.org/book">book</a> and
<a href="http://screencasts.railstutorial.org/">screencast series</a> 
to teach web development with
<a href="http://rubyonrails.org/">Ruby on Rails</a>.

This is the course application for the tutorial.

</p> 

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
    </section>
  </aside>
</div>