app/views/layouts/Desktop/students_copy/config/routes.rb
Rails.application.routes.draw do
  resources :courses do 
    member do
    get :roll 
    end 
  end
  
  resources :students do 
    resources :awards 
    member do 
      get :courses 
      post :course_add 
      post :course_remove 
    end 
  end
end

app/views/layouts/Desktop/students_copy/app/models/award.rb
class Award < ApplicationRecord
    belongs_to :student
end

app/views/layouts/Desktop/students_copy/app/controllers/awards_controller.rb
class AwardsController < ApplicationController
  # before_action :set_award, only: [:show, :edit, :update, :destroy]
  before_action :get_student 
  before_action :set_award, only: [:show, :edit, :update, :destroy]


  # GET /awards
  # GET /awards.json
  def index
    # @awards = Award.all
    @awards = @student.awards
  end

  # GET /awards/1
  # GET /awards/1.json
  def show
  end

  # GET /awards/new
  def new
    @award = Award.new
  end

  # GET /awards/1/edit
  def edit
  end

  # POST /awards
  # POST /awards.json
  def create
    # @award = Award.new(award_params)
    @award = @student.awards.build( award_params)
    
    respond_to do |format|
      if @award.save
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully created.' }
        format.json { render :show, status: :created, location: @award }
      else
        format.html { render :new }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /awards/1
  # PATCH/PUT /awards/1.json
  def update
    respond_to do |format|
      if @award.update(award_params)
        format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully updated.' }
        format.json { render :show, status: :ok, location: @award }
      else
        format.html { render :edit }
        format.json { render json: @award.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /awards/1
  # DELETE /awards/1.json
  def destroy
    @award.destroy
    respond_to do |format|
      format.html { redirect_to student_awards_url(@student), notice: 'Award was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def get_student 
      @student = Student.find( params[:student_id])
    end      

    # Use callbacks to share common setup or constraints between actions.
    def set_award
      #@award = Award.find(params[:id])
      @award = @student.awards.find( params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def award_params
      params.require(:award).permit(:name, :year, :student_id)
    end
end

app/views/layouts/Desktop/students_copy/app/helpers/awards_helper.rb
module AwardsHelper
end

app/views/layouts/Desktop/students_copy/app/views/awards/_form.html.erb
<%= form_for([@student, award]) do |f| %>
  <% if award.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(award.errors.count, "error") %> prohibited this award from being saved:</h2>

      <ul>
      <% award.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>

  <%#div class="field">
    <%#= f.label :student_id %>
    <%#= f.select :student_id, Student.all.collect { |s| [s.name, s.id] } %> 
  <%#/div %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/layouts/Desktop/students_copy/app/views/awards/edit.html.erb
<h1> Editing Award for <%= @student.name %> </h1>

<%= render 'form', award: @award %>

<%= link_to 'Show', [@student, @award] %> | 
<%= link_to 'Back', student_awards_path(@student) %>

app/views/layouts/Desktop/students_copy/app/views/awards/index.html.erb
<p id="notice"><%= notice %></p>

<h1> Awards for <%= @student.name %> </h1 ><% if !@student.awards.empty? %> 

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Student</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @awards.each do |award| %>
      <tr>
        <td><%= award.name %></td>
        <td><%= award.year %></td>
        <td><%= award.student.name %></td>
        <td><%= link_to 'Show', [ @student, award ] %> </td>
        <td><%= link_to 'Edit', edit_student_award_path(@student, award) %> </td> 
        <td><%= link_to 'Destroy', [@student, award], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% else %> 
  <p> <%= @student.given_name %> has no awards yet. </p> 
<% end %>

<%= link_to 'New Award', new_student_award_path(@student) %> | <%= link_to 'Back', @student %>

app/views/layouts/Desktop/students_copy/app/views/awards/new.html.erb
<h1> New Award for <%= @student.name %> </h1>

<%= render 'form', award: @award %>

<%= link_to 'Back', student_awards_path(@student) %>

app/views/layouts/Desktop/students_copy/app/views/awards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @award.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @award.year %>
</p>

<p>
  <strong>Student:</strong>
  <%= @award.student.name %>
</p>

<%= link_to 'Edit', edit_student_award_path(@student, @award) %>|
<%= link_to 'Back', student_awards_path(@student) %>